Repo Redo

diff --git a/create_addon b/create_addon
--- a/create_addon
+++ b/create_addon
@@ -1,82 +1,35 @@
-#!/bin/sh -x
-
-. config/options $1
-
-IFS=" "
-for i in $PKG_ADDON_REQUIRES; do
-  REQUIRES_ADDONNAME=`echo $i | cut -f1 -d ":"`
-  REQUIRES_ADDONVERSION=`echo $i | cut -f2 -d ":"`
-  REQUIRES="$REQUIRES\n    <import addon=\"$REQUIRES_ADDONNAME\" version=\"$REQUIRES_ADDONVERSION\" />"
-done
-
-unset IFS
+#!/bin/sh
 
 if [ -z "$1" ]; then
-  echo "usage: $0 package_name"
+  echo -e "Usage: $0 package_name"
   exit 1
 fi
 
-$SCRIPTS/build $@
-
-printf  "%${INDENT}c CREATE ADDON  $1\n" ' '>&$SILENT_OUT
-export INDENT=$((${INDENT:-1}+$INDENT_SIZE))
-
-if [ -f $PKG_DIR/addon ]; then
-
-  rm -rf $ADDON_BUILD
-
-  $PKG_DIR/addon $@ >&$VERBOSE_OUT
-
-  mkdir -p $ADDON_BUILD/$PKG_ADDON_ID
-    if [ ! -f $ADDON_BUILD/$PKG_ADDON_ID/addon.xml ]; then
-      cp config/addon/addon.xml $ADDON_BUILD/$PKG_ADDON_ID
-      $SED -e "s|@PKG_ADDON_ID@|$PKG_ADDON_ID|g" \
-           -e "s|@PKG_NAME@|$PKG_NAME|g" \
-           -e "s|@ADDON_VERSION@|$PKG_VERSION.$PKG_REV|g" \
-           -e "s|@PKG_ADDON_TYPE@|$PKG_ADDON_TYPE|g" \
-           -e "s|@REQUIRES@|$REQUIRES|g" \
-           -e "s|@PKG_SHORTDESC@|$PKG_SHORTDESC|g" \
-           -e "s|@PKG_SHORTTRANS@|$PKG_SHORTTRANS|g" \
-           -e "s|@OS_VERSION@|$OS_VERSION|g" \
-           -e "s|@PKG_LONGDESC@|$PKG_LONGDESC|g" \
-           -e "s|@PKG_LONGTRANS@|$PKG_LONGTRANS|g" \
-           -i $ADDON_BUILD/$PKG_ADDON_ID/addon.xml
+if [ "$1" = "all" ]; then
+  for script in *; do
+    if [ -x "$script/create_addon" ]; then
+      cd $script
+      if [ "$?" = "0" ]; then
+        ./create_addon
+        if [ "$?" = "0" ]; then
+          echo "$script: done\n"
+        fi
+        cd ../
+      else
+        echo "$script: an error occured\n"
+      fi
     fi
-
-    if [ -f $PKG_DIR/source/default.py ]; then
-      cp -R $PKG_DIR/source/* $ADDON_BUILD/$PKG_ADDON_ID
-    else
-      echo "*** WARNING: You *probably* need at least $PKG_DIR/source/default.py to make your addon work ***"
+  done
+else
+  cd $1
+  if [ "$?" = "0" ]; then
+    ./create_addon
+    if [ "$?" = "0" ]; then
+      echo "$1 done"; exit 0
     fi
-
-    if [ -f $PKG_DIR/icon/icon.png ]; then
-      cp $PKG_DIR/icon/icon.png $ADDON_BUILD/$PKG_ADDON_ID
-    else
-      echo "*** WARNING: It's recommended to have a $PKG_DIR/icon/icon.png file ***"
-    fi
-
-    if [ -f $PKG_DIR/changelog.txt ]; then
-      cp $PKG_DIR/changelog.txt $ADDON_BUILD/$PKG_ADDON_ID
-    else
-      echo "*** WARNING: It's recommended to have a $PKG_DIR/changelog.txt file ***"
-    fi
-
-#  ./xbmc-xml2po -s $ADDON_BUILD/$PKG_ADDON_ID
-#  ./xbmc-checkpo -s $ADDON_BUILD/$PKG_ADDON_ID/resources
-  rm $ADDON_BUILD/$PKG_ADDON_ID/resources/language/*/strings.xml
-
-  cd $ADDON_BUILD
-    echo "*** compressing Addon $PKG_ADDON_ID ... ***"
-    zip -rq9 $PKG_ADDON_ID-$PKG_VERSION.$PKG_REV.zip $PKG_ADDON_ID;
-  cd -
-
-  mkdir -p $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID
-    cp $ADDON_BUILD/$PKG_ADDON_ID-$PKG_VERSION.$PKG_REV.zip $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID
-    cp $ADDON_BUILD/$PKG_ADDON_ID/addon.xml $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID/addon.xml
-    cp $PKG_DIR/changelog.txt $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID/changelog-$PKG_VERSION.$PKG_REV.txt
-    cp $PKG_DIR/icon/icon.png $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID/icon.png
-    if [ -f $PKG_DIR/source/fanart.jpg ]; then
-      cp $PKG_DIR/source/fanart.jpg $TARGET/$ADDONS/$ADDON_VERSION/$PKG_ADDON_ID/fanart.jpg
-    fi
+  else
+    echo "$1 does not exist"
+    exit 1
+  fi
 fi
-
+exit 0
